// <auto-generated />
using DrCarQuotes_Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrCarQuotesData.Migrations
{
    [DbContext(typeof(DrCarQuotesDbContext))]
    [Migration("20230115012610_ChangeCarIdMigration")]
    partial class ChangeCarIdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrCarQuotes_Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Make")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "BMW",
                            Model = "I4",
                            Year = 2012
                        },
                        new
                        {
                            Id = 2,
                            Make = "Audi",
                            Model = "A6",
                            Year = 2005
                        },
                        new
                        {
                            Id = 3,
                            Make = "Fiat",
                            Model = "500x",
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            Make = "Toyota",
                            Model = "Hilux",
                            Year = 2015
                        },
                        new
                        {
                            Id = 5,
                            Make = "Acura",
                            Model = "Enclave",
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            Make = "GMC",
                            Model = "Canyon",
                            Year = 2020
                        },
                        new
                        {
                            Id = 7,
                            Make = "Ford",
                            Model = "Edge",
                            Year = 2016
                        },
                        new
                        {
                            Id = 8,
                            Make = "Ford",
                            Model = "Escape",
                            Year = 2021
                        },
                        new
                        {
                            Id = 9,
                            Make = "Audi",
                            Model = "A4",
                            Year = 2020
                        },
                        new
                        {
                            Id = 10,
                            Make = "Chevrolet",
                            Model = "Cruze",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("DrCarQuotes_Domain.Entities.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "127-4 Willets Point Blvd, Corona, NY 11368, United States",
                            Name = "Sam Auto Shop",
                            Phone = "+1234588823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 2,
                            Address = "724 State Rd., Philadelphia, PA 19136, United States",
                            Name = "Repair Guys",
                            Phone = "+1384588223",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 3,
                            Address = "520 Florida Ave NE, Washington, DC 20002, United States",
                            Name = "Automotive Brothers",
                            Phone = "+1344588823",
                            ZipCode = "20002"
                        },
                        new
                        {
                            Id = 4,
                            Address = "261 Shirlington Rd, Arlington, VA 22206, United States",
                            Name = "Hill Auto Repair",
                            Phone = "+1684580823",
                            ZipCode = "22206"
                        },
                        new
                        {
                            Id = 5,
                            Address = "143 Build America Dr, Woodbridge, VA 22191, United States",
                            Name = "A & Y Auto Masters",
                            Phone = "+1784585823",
                            ZipCode = "22191"
                        },
                        new
                        {
                            Id = 6,
                            Address = "3600 Rhawn St, Philadelphia, PA 19136, United States",
                            Name = "Car Doctors Auto Shop",
                            Phone = "+1984548823",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 7,
                            Address = "567 Elm St, Corona, NY 11368, United States",
                            Name = "Auto Express",
                            Phone = "+1984548823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 8,
                            Address = "890 Main St, Corona, NY 11368, United States",
                            Name = "Car Care Pro",
                            Phone = "+1784585823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 9,
                            Address = "123 Park Ave, Corona, NY 11368, United States",
                            Name = "Car Repair Guys",
                            Phone = "+1684580823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 10,
                            Address = "456 Pine St, Philadelphia, PA 19136, United States",
                            Name = "Master Auto Shop",
                            Phone = "+1344588823",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 11,
                            Address = "789 Oak St, Philadelphia, PA 19136, United States",
                            Name = "Pro Auto Repair",
                            Phone = "+1384588223",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 12,
                            Address = "321 Maple St, Philadelphia, PA 19136, United States",
                            Name = "Auto Repair Pro",
                            Phone = "+1234588823",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 13,
                            Address = "912 Elm St, Corona, NY 11368, United States",
                            Name = "Auto Repair Zone",
                            Phone = "+1984548823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 14,
                            Address = "890 Main St, Corona, NY 11368, United States",
                            Name = "Auto Care Guys",
                            Phone = "+1784585823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 15,
                            Address = "123 Park Ave, Corona, NY 11368, United States",
                            Name = "Auto Repair Pro",
                            Phone = "+1684580823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 16,
                            Address = "456 Pine St, Philadelphia, PA 19136, United States",
                            Name = "Car Repair Pro",
                            Phone = "+1344588823",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 17,
                            Address = "789 Oak St, Philadelphia, PA 19136, United States",
                            Name = "Auto Repair Guys",
                            Phone = "+1384588223",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 18,
                            Address = "321 Maple St, Philadelphia, PA 19136, United States",
                            Name = "Auto Repair Express",
                            Phone = "+1234588823",
                            ZipCode = "19136"
                        },
                        new
                        {
                            Id = 19,
                            Address = "567 Elm St, Corona, NY 11368, United States",
                            Name = "Auto Repair Shop",
                            Phone = "+1984548823",
                            ZipCode = "20374"
                        },
                        new
                        {
                            Id = 20,
                            Address = "890 Main St, Corona, NY 11368, United States",
                            Name = "Auto Repair Pro",
                            Phone = "+1784585823",
                            ZipCode = "20374"
                        });
                });

            modelBuilder.Entity("DrCarQuotes_Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RepairServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RepairServiceId");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            MechanicId = 1,
                            Price = 50m,
                            RepairServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            MechanicId = 2,
                            Price = 75m,
                            RepairServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            MechanicId = 3,
                            Price = 100m,
                            RepairServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            MechanicId = 4,
                            Price = 125m,
                            RepairServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            MechanicId = 5,
                            Price = 150m,
                            RepairServiceId = 5
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            MechanicId = 6,
                            Price = 200m,
                            RepairServiceId = 6
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            MechanicId = 7,
                            Price = 225m,
                            RepairServiceId = 1
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            MechanicId = 8,
                            Price = 250m,
                            RepairServiceId = 2
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            MechanicId = 9,
                            Price = 275m,
                            RepairServiceId = 3
                        },
                        new
                        {
                            Id = 10,
                            CarId = 1,
                            MechanicId = 10,
                            Price = 300m,
                            RepairServiceId = 4
                        },
                        new
                        {
                            Id = 11,
                            CarId = 1,
                            MechanicId = 11,
                            Price = 325m,
                            RepairServiceId = 5
                        },
                        new
                        {
                            Id = 12,
                            CarId = 2,
                            MechanicId = 12,
                            Price = 350m,
                            RepairServiceId = 6
                        },
                        new
                        {
                            Id = 13,
                            CarId = 3,
                            MechanicId = 13,
                            Price = 375m,
                            RepairServiceId = 1
                        },
                        new
                        {
                            Id = 14,
                            CarId = 1,
                            MechanicId = 14,
                            Price = 400m,
                            RepairServiceId = 2
                        },
                        new
                        {
                            Id = 15,
                            CarId = 5,
                            MechanicId = 15,
                            Price = 425m,
                            RepairServiceId = 3
                        },
                        new
                        {
                            Id = 16,
                            CarId = 6,
                            MechanicId = 16,
                            Price = 450m,
                            RepairServiceId = 4
                        },
                        new
                        {
                            Id = 17,
                            CarId = 7,
                            MechanicId = 17,
                            Price = 475m,
                            RepairServiceId = 5
                        },
                        new
                        {
                            Id = 18,
                            CarId = 8,
                            MechanicId = 18,
                            Price = 500m,
                            RepairServiceId = 6
                        },
                        new
                        {
                            Id = 19,
                            CarId = 9,
                            MechanicId = 19,
                            Price = 525m,
                            RepairServiceId = 1
                        },
                        new
                        {
                            Id = 20,
                            CarId = 10,
                            MechanicId = 20,
                            Price = 550m,
                            RepairServiceId = 2
                        });
                });

            modelBuilder.Entity("DrCarQuotes_Domain.Entities.RepairService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RepairServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oil Change"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brake Pads"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Windshield Wiper"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Air Filter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Spark Plug"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tire Change"
                        });
                });

            modelBuilder.Entity("DrCarQuotes_Domain.Entities.Quote", b =>
                {
                    b.HasOne("DrCarQuotes_Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrCarQuotes_Domain.Entities.Mechanic", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrCarQuotes_Domain.Entities.RepairService", "Repair")
                        .WithMany()
                        .HasForeignKey("RepairServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Mechanic");

                    b.Navigation("Repair");
                });
#pragma warning restore 612, 618
        }
    }
}
